#!/bin/env python
import csv
import sys

import bitvector

if __name__ == '__main__':
    cell_type = sys.argv[2]
    mask = bitvector.bitvector(int(x) for x in sys.argv[3][1:-1].split(','))
    with open(sys.argv[1]) as f:
        ps, annots = zip(*sorted((float(row['p']), 
                                  1 if int(row[cell_type]) & mask else 0)
                                 for row in csv.DictReader(f)))
    print(len(annots))
    for a in annots:
        print(a)
